services:
  boreal.chat:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    image: boreal.chat
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
    volumes:
      - .env:/app/.env
