services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: borealchat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  electric:
    image: electricsql/electric
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/borealchat?sslmode=disable
      # Not suitable for production. Only use insecure mode in development or if you've otherwise secured the Electric API.
      # See https://electric-sql.com/docs/guides/security
      ELECTRIC_INSECURE: true
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  mailpit:
    image: axllent/mailpit:latest
    volumes:
      - mailpit-data:/data
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: "1"
      MP_SMTP_AUTH_ALLOW_INSECURE: "1"

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_REGION_NAME: us-east-1
      # Webhook notification configuration
      MINIO_NOTIFY_WEBHOOK_ENABLE_primary: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_primary: "http://172.17.0.1:5173/api/webhook/s3"
      MINIO_NOTIFY_WEBHOOK_AUTH_TOKEN_primary: ""
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 30s
      retries: 3

  minio-setup:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      echo 'Configuring MinIO webhook notifications...';
      mc alias set local http://minio:9000 minioadmin minioadmin;
      echo 'Creating bucket if it does not exist...';
      mc mb local/borealchat-files --ignore-existing;
      echo 'Setting up webhook notification...';
      mc event add local/borealchat-files arn:minio:sqs::primary:webhook --event put;
      echo 'Webhook notification setup complete!';
      echo 'Configuration:';
      echo '- Bucket: borealchat-files';
      echo '- Webhook: http://172.17.0.1:5173/api/webhook/s3';
      echo '- Events: s3:ObjectCreated:Put';
      mc event list local/borealchat-files;
      "
    restart: "no"

volumes:
  postgres-data:
  redis-data:
  mailpit-data:
  minio-data:
