// This file is auto-generated by scripts/fetchModelFeatures.ts.
// Do not edit this file manually.

import type { ModelId } from "./models";

export const GENERATED_AT = "2025-08-07T19:25:13.915Z";

export type ModelFeatures = {
  contextLength: number;
  pricing: {
    prompt: number;
    completion: number;
    image: number;
    web_search: number;
    request: number;
  };
  inputModalities: ("text" | "image" | "audio" | "video" | "file")[];
};

export const MODEL_FEATURES: Partial<Record<ModelId, ModelFeatures>> = {
  "openai/gpt-5-chat": {
    contextLength: 400000,
    pricing: {
      prompt: 0.00000125,
      completion: 0.00001,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["file", "image", "text"],
  },
  "openai/gpt-5-mini": {
    contextLength: 400000,
    pricing: {
      prompt: 2.5e-7,
      completion: 0.000002,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text", "image", "file"],
  },
  "openai/gpt-5-nano": {
    contextLength: 400000,
    pricing: {
      prompt: 5e-8,
      completion: 4e-7,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text", "image", "file"],
  },
  "openai/gpt-oss-120b": {
    contextLength: 131072,
    pricing: {
      prompt: 9e-8,
      completion: 4.5e-7,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text"],
  },
  "openai/gpt-oss-20b": {
    contextLength: 131072,
    pricing: {
      prompt: 4e-8,
      completion: 1.6e-7,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text"],
  },
  "z-ai/glm-4.5": {
    contextLength: 131072,
    pricing: {
      prompt: 2e-7,
      completion: 2e-7,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text"],
  },
  "z-ai/glm-4.5-air:free": {
    contextLength: 131072,
    pricing: {
      prompt: 0,
      completion: 0,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text"],
  },
  "z-ai/glm-4.5-air": {
    contextLength: 128000,
    pricing: {
      prompt: 2e-7,
      completion: 0.0000011,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text"],
  },
  "qwen/qwen3-coder": {
    contextLength: 262144,
    pricing: {
      prompt: 1.999188e-7,
      completion: 8.00064e-7,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text"],
  },
  "moonshotai/kimi-k2:free": {
    contextLength: 32768,
    pricing: {
      prompt: 0,
      completion: 0,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text"],
  },
  "moonshotai/kimi-k2": {
    contextLength: 63000,
    pricing: {
      prompt: 1.4e-7,
      completion: 0.00000249,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text"],
  },
  "x-ai/grok-4": {
    contextLength: 256000,
    pricing: {
      prompt: 0.000003,
      completion: 0.000015,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["image", "text"],
  },
  "google/gemini-2.5-flash": {
    contextLength: 1048576,
    pricing: {
      prompt: 3e-7,
      completion: 0.0000025,
      image: 0.001238,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["file", "image", "text", "audio"],
  },
  "google/gemini-2.5-pro-preview": {
    contextLength: 1048576,
    pricing: {
      prompt: 0.00000125,
      completion: 0.00001,
      image: 0.00516,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["file", "image", "text"],
  },
  "deepseek/deepseek-r1-0528:free": {
    contextLength: 163840,
    pricing: {
      prompt: 0,
      completion: 0,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text"],
  },
  "deepseek/deepseek-r1-0528": {
    contextLength: 163840,
    pricing: {
      prompt: 1.7992692e-7,
      completion: 7.200576e-7,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text"],
  },
  "anthropic/claude-opus-4": {
    contextLength: 200000,
    pricing: {
      prompt: 0.000015,
      completion: 0.000075,
      image: 0.024,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["image", "text"],
  },
  "anthropic/claude-sonnet-4": {
    contextLength: 200000,
    pricing: {
      prompt: 0.000003,
      completion: 0.000015,
      image: 0.0048,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["image", "text"],
  },
  "qwen/qwen3-30b-a3b": {
    contextLength: 40960,
    pricing: {
      prompt: 1.999188e-8,
      completion: 8.00064e-8,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text"],
  },
  "openai/o4-mini-high": {
    contextLength: 200000,
    pricing: {
      prompt: 0.0000011,
      completion: 0.0000044,
      image: 0.0008415,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["image", "text", "file"],
  },
  "openai/o4-mini": {
    contextLength: 200000,
    pricing: {
      prompt: 0.0000011,
      completion: 0.0000044,
      image: 0.0008415,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["image", "text"],
  },
  "openai/gpt-4.1": {
    contextLength: 1047576,
    pricing: {
      prompt: 0.000002,
      completion: 0.000008,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["image", "text", "file"],
  },
  "openai/gpt-4.1-mini": {
    contextLength: 1047576,
    pricing: {
      prompt: 4e-7,
      completion: 0.0000016,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["image", "text", "file"],
  },
  "openai/gpt-4.1-nano": {
    contextLength: 1047576,
    pricing: {
      prompt: 1e-7,
      completion: 4e-7,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["image", "text", "file"],
  },
  "x-ai/grok-3-mini-beta": {
    contextLength: 131072,
    pricing: {
      prompt: 3e-7,
      completion: 5e-7,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text"],
  },
  "x-ai/grok-3-beta": {
    contextLength: 131072,
    pricing: {
      prompt: 0.000003,
      completion: 0.000015,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text"],
  },
  "meta-llama/llama-4-maverick": {
    contextLength: 1048576,
    pricing: {
      prompt: 1.5e-7,
      completion: 6e-7,
      image: 0.0006684,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text", "image"],
  },
  "meta-llama/llama-4-scout": {
    contextLength: 1048576,
    pricing: {
      prompt: 8e-8,
      completion: 3e-7,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text", "image"],
  },
  "deepseek/deepseek-chat-v3-0324:free": {
    contextLength: 163840,
    pricing: {
      prompt: 0,
      completion: 0,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text"],
  },
  "deepseek/deepseek-chat-v3-0324": {
    contextLength: 163840,
    pricing: {
      prompt: 1.7992692e-7,
      completion: 7.200576e-7,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text"],
  },
  "anthropic/claude-3.7-sonnet:thinking": {
    contextLength: 200000,
    pricing: {
      prompt: 0.000003,
      completion: 0.000015,
      image: 0.0048,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text", "image"],
  },
  "google/gemini-2.0-flash-001": {
    contextLength: 1048576,
    pricing: {
      prompt: 1e-7,
      completion: 4e-7,
      image: 0.0000258,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text", "image", "file", "audio"],
  },
  "google/gemini-2.0-flash-exp:free": {
    contextLength: 1048576,
    pricing: {
      prompt: 0,
      completion: 0,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text", "image"],
  },
  "meta-llama/llama-3.3-70b-instruct:free": {
    contextLength: 65536,
    pricing: {
      prompt: 0,
      completion: 0,
      image: 0,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text"],
  },
  "anthropic/claude-3.5-sonnet": {
    contextLength: 200000,
    pricing: {
      prompt: 0.000003,
      completion: 0.000015,
      image: 0.0048,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text", "image"],
  },
  "openai/gpt-4o-mini": {
    contextLength: 128000,
    pricing: {
      prompt: 1.5e-7,
      completion: 6e-7,
      image: 0.000217,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text", "image", "file"],
  },
  "openai/gpt-4o": {
    contextLength: 128000,
    pricing: {
      prompt: 0.0000025,
      completion: 0.00001,
      image: 0.003613,
      web_search: 0,
      request: 0,
    },
    inputModalities: ["text", "image", "file"],
  },
};
