name: CI

on:
  push:
  merge_group:

env:
  FORCE_COLOR: 3

jobs:
  lint:
    name: Lint
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/setup

      - name: Lint
        run: pnpm lint

  format:
    name: Format
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/setup

      - name: Format
        run: pnpm format

  typecheck:
    name: Typecheck
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/setup

      - name: Typecheck
        run: pnpm typecheck

  test:
    name: Test
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/setup

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Pull Docker images
        run: docker compose pull

      - name: Test
        run: pnpm test
